{"name": "test_mul[failed]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3", "trace": "self = <calctest.calc_case.calccase.TestCalcutor object at 0x0000023289EA8160>\nget_calc = <calc_class.calcclass.Calculator object at 0x0000023289E56C70>\nget_mul_datas = [1, 2, 3]\n\n    @allure.story(\"测试乘法\")\n    @pytest.mark.run(order=3)#order控制方法执行顺序\n    def test_mul(self, get_calc, get_mul_datas):\n        # 步骤说明\n        with allure.step(\"乘法计算\"):\n            result = get_calc.mul(get_mul_datas[0], get_mul_datas[1])#获取测试数据\n        if isinstance(result, float):#判断数据类型，如果是浮点数，强制保留小数点后两位\n            result = round(result, 2)\n>       assert result == get_mul_datas[2]#断言:判断是否相等，相等则pass，不相等则fail\nE       assert 2 == 3\n\ncalc_case\\calccase.py:39: AssertionError"}, "steps": [{"name": "乘法计算", "status": "passed", "start": 1612344470926, "stop": 1612344470926}], "parameters": [{"name": "get_mul_datas", "value": "[1, 2, 3]"}], "start": 1612344470926, "stop": 1612344470926, "uuid": "1317291c-34af-4936-bfb1-64e6a111fbbe", "historyId": "ead80cf806841aa60e125e52b1ca9eff", "testCaseId": "21f15c242c33a83a01d75502ce5677b8", "fullName": "calc_case.calccase.TestCalcutor#test_mul", "labels": [{"name": "story", "value": "测试乘法"}, {"name": "feature", "value": "计算器测试"}, {"name": "tag", "value": "run(order=3)"}, {"name": "parentSuite", "value": "calc_case"}, {"name": "suite", "value": "calccase"}, {"name": "subSuite", "value": "TestCalcutor"}, {"name": "host", "value": "SC-202005180944"}, {"name": "thread", "value": "18704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "calc_case.calccase"}]}